
quarkus:
   datasource:
      db-kind: oracle 
      jdbc:
        driver: oracle.jdbc.OracleDriver
        url:  jdbc:oracle:thin:@1.1.1.2:8080NaN/test
      username: ora
      password: sys
# drop and create the database at startup (use `update` to only update the schema)
   hibernate-orm:
      database:
         generation: update
